# Generated by Django 4.1.4 on 2022-12-25 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('rows', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='FiFa.matches')),
                ('ticket_seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FiFa.seats')),
            ],
        ),
        migrations.AddField(
            model_name='seats',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_venue', to='FiFa.stadiums'),
        ),
        migrations.AddField(
            model_name='matches',
            name='linesman_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linesman_1', to='FiFa.referees'),
        ),
        migrations.AddField(
            model_name='matches',
            name='linesman_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linesman_2', to='FiFa.referees'),
        ),
        migrations.AddField(
            model_name='matches',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee', to='FiFa.referees'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='FiFa.teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='FiFa.teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='FiFa.stadiums'),
        ),
    ]
